"""The threshold numbers, at SEED time only — never at run time.

A run reads thresholds from one place: the portfolio's `risk_limits` rows. This
module is what puts the first rows there, and it is deliberately unreachable
from the engine: `analytics/limits.py` does not import it and must never start
to. That import direction — not a test, not a convention — is what keeps
`check_limits` from ever having a number of its own to fall back on.

Before this, the same eight thresholds were written down in three places that
disagreed: configs/risk_limits.yaml (9 blocks, one of which no code read), the
13-row seed CSV generated by scripts/_generate_seed_data.py, and 16 hardcoded
defaults inside check_limits' own cfg() closure. The literals were the dangerous
copy: the API container has no /app/configs at all, so a missing YAML did not
fail — it logged a warning and promoted all 16 to the live thresholds.

Editing a number here changes what NEW portfolios are seeded with. It does not
touch a row that already exists; migrations only ever insert what is missing.
"""

from __future__ import annotations

from exposure_workbench.analytics.limits import LIMIT_SPECS, REQUIRED_LIMIT_TYPES

# Every limit type a run evaluates, as (warning, breach) fractions. Each becomes
# one row with entity_id NULL — the portfolio-wide default for that check.
SEED_DEFAULTS: dict[str, tuple[float, float]] = {
    "daily_loss":             (0.020, 0.030),
    "var_95":                 (0.025, 0.035),
    "expected_shortfall_95":  (0.035, 0.050),
    "rolling_volatility_30d": (0.18,  0.25),
    "gross_exposure":         (1.10,  1.20),
    "sector_concentration":   (0.40,  0.50),
    "issuer_concentration":   (0.15,  0.20),
    "stress_loss":            (0.060, 0.080),
}

# The demo book's own policy, tighter than the default for four names. Keyed
# (limit_type, entity_id); entity_type is not stored here because the alert
# takes it from LIMIT_SPECS.
#
# The retired seed CSV also carried Technology 0.40/0.50 and NVDA/AAPL/MSFT
# 0.15/0.20. Those are dropped: a row that restates the default is the same
# number written twice, and the second copy is the one that goes stale.
DEMO_OVERRIDES: dict[tuple[str, str], tuple[float, float]] = {
    ("sector_concentration", "Consumer_Discretionary"): (0.15, 0.20),
    ("sector_concentration", "Financials"):             (0.20, 0.30),
    ("sector_concentration", "Fixed_Income"):           (0.20, 0.30),
    ("issuer_concentration", "LLY"):                    (0.12, 0.18),
}

# Seeding a type the engine cannot evaluate is how `stress_loss_tech` came to be
# served to users as policy in force for a year without ever being looked up.
assert set(SEED_DEFAULTS) == REQUIRED_LIMIT_TYPES, (
    "SEED_DEFAULTS must cover exactly the limit types check_limits evaluates: "
    f"missing {sorted(REQUIRED_LIMIT_TYPES - set(SEED_DEFAULTS))}, "
    f"unknown {sorted(set(SEED_DEFAULTS) - REQUIRED_LIMIT_TYPES)}"
)
assert all(
    lt in LIMIT_SPECS and LIMIT_SPECS[lt].scope == "entity"
    for lt, _ in DEMO_OVERRIDES
), "an override must name a limit type that is looked up per entity"
